### ISSUE TITLE
space-before-function-paren and indent

### ISSUE THREAD

**Issue by jandockx** [npetruzzelli/prettier-config-standard#6]
Am I missing something, or doesn't this work? Standardjs still reports

- Missing space before function parentheses. (space-before-function-paren)
- Expected indentation of 10 spaces but found 8. (indent)

`package.json`:

```json
{
  […]
  "devDependencies": {
    […]
    "eslint": "^8.19.0",
    […]
    "prettier": "^2.7.1",
    "prettier-config-standard": "^5.0.0",
    […]
    "standard": "^17.0.0",
    […]
  },
  "prettier": "prettier-config-standard",
  […]
}
```

execute:

```shell
❯ npx prettier --write .
[…]
❯ npx standard
standard: Use JavaScript Standard Style (https://standardjs.com)
standard: Run `standard --fix` to automatically fix some problems.
[…]
[…]:32:20: Missing space before function parentheses. (space-before-function-paren)
[…]:96:1: Expected indentation of 10 spaces but found 8. (indent)
[…]
```

**Comment by npetruzzelli** [comment]
This is a prettier config designed to be consistent with JavaScript Standard Style (JSS). It is also intended to be accessible so that non-JavaScript Prettier configs can use it as a base or use it as the content for overrides targeting js/jsx/ts/tsx/etc...

JSS, when used directly through `standard` is not configurable: <https://standardjs.com/#i-disagree-with-rule-x-can-you-change-it>

This Prettier config is intended to be used when Prettier is run after ESLint or Standard, or as a part of ESLint config where both standard and prettier are consumed as ESLint Plugins instead of individual processes. Part of working with Prettier means disabling rules that could conflict with Prettier or otherwise managing them.

If you are looking to use standard and prettier together, you will need todo something similar to: [eslint-config-prettier-standard](https://github.com/npetruzzelli/eslint-config-prettier-standard) or find a different binary that combines prettier and standard as it own binary or API.

**Comment by npetruzzelli** [comment]
Closed as inactive.
